<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\Blog;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // User::truncate();
        User::factory()->create(["name"=>"Aung Thu Zaw","username"=>"@aungthuzaw","email"=>"aungthuzaw@gmail.com","password"=>"123456"]);
        User::factory()->create(["name"=>"Xyder","username"=>"@xyder","email"=>"xyder@gmail.com","password"=>"123456"]);

        // Blog::truncate();

        // Frontend Posts
        Blog::factory()->create(["category_id"=>1,"user_id"=>1,"slug"=>"html-post","title"=>"About of HTML-5","intro"=>"This is a HTML-5 Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/BXdyvzGUg8swdiJ2PInRTOVEOzOXMgojFOHb8pRg.jpg"]);
        Blog::factory()->create(["category_id"=>1,"user_id"=>2,"slug"=>"css-post","title"=>"About of Css-3","intro"=>"This is a Css-3 Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/h6E6sHnEH8AncaRl53o9KSeVj1GEUZhbM8otjHsq.jpg"]);
        Blog::factory()->create(["category_id"=>1,"user_id"=>2,"slug"=>"javascript-post","title"=>"About of Javascript","intro"=>"This is a Javascript Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/kiW7FZK4MbH0u5dLSHW2qZ5iYgD18aTNufIpQuuk.jpg"]);
        Blog::factory()->create(["category_id"=>1,"user_id"=>1,"slug"=>"jquery-post","title"=>"About of Jquery","intro"=>"This is a Jquery Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/SIDrqPf9du2nYmqGadNQQTBAw3WFdJMG2GTzie7K.webp"]);
        Blog::factory()->create(["category_id"=>1,"user_id"=>1,"slug"=>"bootstrap-post","title"=>"About of Bootstrap-5","intro"=>"This is a Bootstrap-5 Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/RCNttEOvJq1E2fpzFRz5Y55DrZp696GOonKqA7jy.jpg"]);

        // Backend Posts
        Blog::factory()->create(["category_id"=>2,"user_id"=>2,"slug"=>"php-post","title"=>"About of Php","intro"=>"This is a Php Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/0UBG91pXVXHhYI1SDXrouYHY5QVrqTPDIiJXBPWy.png"]);
        Blog::factory()->create(["category_id"=>2,"user_id"=>1,"slug"=>"mysql-post","title"=>"About of Mysql","intro"=>"This is a Mysql Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/YKd5MO1B24ytAnnD8jTx5blh8roIN2Ly6AgF9PE4.avif"]);
        Blog::factory()->create(["category_id"=>2,"user_id"=>2,"slug"=>"nodejs-post","title"=>"About of Node Js","intro"=>"This is a Node Js Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/2hl0aaF7GlBx1x3LXmEIzWjW8d7t8HeKeaGfwu0w.png"]);
        Blog::factory()->create(["category_id"=>2,"user_id"=>1,"slug"=>"laravel-post","title"=>"About of Laravel","intro"=>"This is a Laravel Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/wSmoHAgyvqY52zgWy1duXWDS81NjtbhlP0XoHCQK.jpg"]);
        Blog::factory()->create(["category_id"=>2,"user_id"=>2,"slug"=>"firebase-post","title"=>"About of Firebase","intro"=>"This is a Firebase Intro.","body"=>"Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequatur tempore iste, tempora aperiam velit placeat explicabo minima quam consequuntur corrupti, eaque quo, repellat dignissimos dicta incidunt voluptas nam itaque debitis ipsam nisi neque fugit asperiores laboriosam accusantium? Nobis deleniti, alias dolorem dicta, deserunt ex adipisci quisquam quam nostrum ut doloremque error voluptate commodi, pariatur reiciendis aperiam quos maxime accusantium earum quia magnam totam omnis! Numquam, optio laboriosam odio facilis magnam saepe eius in, tempore perferendis tenetur illum quae amet modi ex dolorem est animi nobis corrupti ea. Vel molestias exercitationem iusto quia dolores nam natus aspernatur illo distinctio, voluptatem eius.","thumbnail"=>"/thumbnails/OhjqlSogiaXjrMWmYW7QRDvOnSY1PHnrHHrLps1a.jpg"]);


        // Category::truncate();

        Category::factory()->create(["slug"=>"frontend-posts","name"=>"Frontend Blogs"]);

        Category::factory()->create(["slug"=>"backend-posts","name"=>"Backend Blogs"]);
    }
}
